[package]
name = "hd44780-ntb"
version = "0.0.1"
authors = ["Michael Cummings <dragonrun1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
